version: '2'
services:
    blogapp-app:
        image: blogapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://blogapp-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=blogApp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    blogapp-mongodb:
        extends:
            file: mongodb.yml
            service: blogapp-mongodb
